import React, { useState } from 'react';
import CourseFilter from './courseFilter';

function CourseHead() {

    const data: any = [
        {
            id: 1,
            title: "Threading",
            li1: "Theory",
            li2: "Eyebrows",
            li3: "Upper lips",
            li4: "Dimple",
            li5: "Full face",
            li6: "Practical",
        },
        {
            id: 1,
            title: "Facial",
            li1: "Theory",
            li2: "Clean-up",
            li3: "Facial strokes",
            li4: "Facial types",
            li5: "Applying methods",
            li6: "Knowledge about skin types",
            li7: "Practical",
        },
        {
            id: 1,
            title: "Hand facial",
            li1: "Theory",
            li2: "Application methods",
            li3: "Half hands",
            li4: "Full hands",
            li5: "Practical",
        },
        {
            id: 1,
            title: "Bleach",
            li1: "Theory",
            li2: "Knowledge about skin types",
            li3: "Bleach cream with herbal",
            li4: "Application technique",
            li5: "Bleach cream based",
            li6: "Practical",
        },
        {
            id: 1,
            title: "Leg facial",
            li1: "Theory",
            li2: "Application methods",
            li3: "Half legs",
            li4: "Full legs",
            li5: "Practical",
        },
        {
            id: 1,
            title: "Manicure",
            li1: "Palm",
            li2: "Full hands",
            li3: "Knowledge about Nails",
        },
        {
            id: 1,
            title: "Pedicure",
            li1: "Half legs",
            li2: "Full legs",
            li3: "Knowledge about Nails & Foot",
        },
        {
            id: 1,
            title: "Waxing",
            li1: "Knowledge about application",
            li2: "Mixing methods",
            li3: "Hand waxing",
            li4: "Leg waxing",
        },
        {
            id: 1,
            title: "Oil massage",
            li1: "Head massage",
            li2: "Hot -oil massage",
            li3: "Strokes",
            li4: "Applying methods",
        },
        {
            id: 1,
            title: "Hair colouring",
            li1: "Henna based 2types",
            li2: "Dye-based",
            li3: "Application techniques",
            li4: "Hair wash techniques",
        },
        {
            id: 1,
            title: "Haircuts",
            li1: "Straight cut",
            li2: "U-cut",
            li3: "Bob cut",
            li4: "V-cut",
            li5: "Mushroom cut",
        },
        {
            id: 1,
            title: "Mehandi",
            li1: "Basic Mehandi",
            li2: "application",
            li3: "Hands",
            li4: "Legs",
        },
        {
            id: 1,
            title: "Nail polish",
            li1: "Hand nails",
            li2: "Foot nails",
        },
        {
            id: 1,
            title: "Basic Make-up",
            li1: "Knowledge about products",
            li2: "Face makeup",
            li3: "Muhurtham look",
            li4: "Reception look",
        },
        {
            id: 1,
            title: "Hairstyles",
            li1: "Muhurtham hairstyle",
            li2: "Reception hairstyle",
            li3: "Basic knowledge about hairsprays",
        },
        {
            id: 1,
            title: "Saree",
            li1: "Saree draping - 2 types",
        },
        {
            id: 1,
            title: "Flowers",
            li1: "Artificial flowers",
            li2: "arranging for brides",
            li3: "Real flower setting for brides",
        },
        {
            id: 2,
            title: "Skin",
            li1: "skin anatomy",
            li2: "Advanced skin treatment",
            li3: "Deep knowledge about skin.",
            li4: "Knowledge about skin layers",
            li5: "Skin analysing",
        },
        {
            id: 2,
            title: "Advanced Skin Treatments",
            li1: "Acne treatments",
            li2: "Pigment treatments",
            li3: "Whitening treatment.",
            li4: "Peels",
            li5: "Knowledge about peels",
            li6: "Hydra & Galvanic facial",
            li7: "High frequency treatment",
        },
        {
            id: 2,
            title: "Hair",
            li1: "Hair anatomy",
            li2: "Hair analysing",
            li3: "Layers about hair",
            li4: "Deep knowledge about hair",
        },
        {
            id: 2,
            title: "Advanced Hair Treatments",
            li1: "Hair spa",
            li2: "Herbal hair spa",
            li3: "Soothening treatment",
            li4: "Balancing treatment",
            li5: "Anti-dandruff treatment",
            li6: "Renew-C treatment",
            li7: "Straightening & Keratin treatment ",
        },
        {
            id: 2,
            title: "Haircuts",
            li1: "Butter fly cut",
            li2: "Layer cut",
            li3: "Feather cut",
            li4: "Multi-layer cut",
            li5: "Step cut",
            li6: "Face bangs",
            li7: "Creativity cut ",
        },
        {
            id: 2,
            title: "Advanced Manicure",
            li1: "Manicure spa",
            li2: "Bubblegum manicure",
            li3: "Knowledge of tools",
            li4: "Handling methods",
            li5: "Strokes & techniques",
            li6: "Nail polishing",
        },
        {
            id: 2,
            title: "Advanced Pedicure",
            li1: "Pedicure spa",
            li2: "Knowledge about tools",
            li3: "Machine handling technique",
            li4: "Bubblegum pedicure",
            li5: "Heel-Peel treatment",
            li6: "Strokes & techniques",
        },
        {
            id: 2,
            title: "Waxing",
            li1: "Deep knowledge about wax",
            li2: "Machine handling technique",
            li3: "Machine Rica wax",
            li4: "Pearl wax",
            li5: "Bean wax",
            li6: "Chocolate wax",
            li7: "Cold wax",
        },
        {
            id: 2,
            title: "Knowledge about tools",
            li1: "Scissor practicing",
            li2: "Comb & handling technique",
            li3: "Dryer knowledge",
            li4: "Bouney blow dry",
            li5: "blast dry technique",
        },
        {
            id: 2,
            title: "Hair Colouring",
            li1: "Knowledge about colour & developer",
            li2: "Global colouring",
            li3: "Grey hair cover with Global colouring",
            li4: "fashion colour",
            li5: "Knowledge about product usage",
            li6: "Root touch-ups",
            li7: "Free & Highlightning technique",
        },
        {
            id: 2,
            title: "WARTS REMOVING  ",
            li1: "Face warts removing",
            li2: "Body warts removing",
        },
        {
            id: 3,
            title: "Make-up",
            li1: "knowledge about skincare & products",
            li2: "Skin types knowledge",
            li3: "Skin tones knowledge",
            li4: "knowledge about face shapes.",
            li5: "Brush knowledge",
            li6: "Product knowledge",
            li7: "Sponge knowledge",
        },
        {
            id: 3,
            title: "Make-up",
            li1: "Knowledge about foundation shades",
            li2: "Skin colour corrections",
            li3: "Conceiving techniques",
            li4: "Foundation mixing technique",
            li5: "Baking techniques",
            li6: "Setting techniques",
            li7: "Blush application",
        },
        {
            id: 3,
            title: "Make-up",
            li1: "Highlighting techniques",
            li2: "Contour techniques big to small",
            li3: "Eye Make-up knowledge",
            li4: "Eye Liner techniques",
            li5: "Eve-Shadows, Pigments knowledge",
            li6: "Glitters knowledge",
            li7: "Eyebrow defining techniques",
        },
        {
            id: 3,
            title: "Make-up",
            li1: "False Lash fiving",
            li2: "Lens application",
            li3: "Lip-lining techniques",
            li4: "Knowledge about Glossy & Matt",
            li5: "Lipstick mixing techniques",
            li6: "Transfer proof make-up look",
        },
        {
            id: 3,
            title: "Make-up",
            li1: "HD make-up look",
            li2: "Waterproof make-up",
            li3: "No make-up look like",
            li4: "cine make-up",
            li5: "Party make-up look",
            li6: "Muhurtham look",
            li7: "Reception look",
        },
        {
            id: 3,
            title: "Make-up",
            li1: "Self grooming",
            li2: "Flowers & Jewels",
            li3: "Client management",
        },
        {
            id: 3,
            title: "Hairstyle",
            li1: "Understanding the hair texture",
            li2: "Hair preparations",
            li3: "Blow dry setting",
            li4: "Knowledge about crimper",
            li5: "Knowledge about tongs",
            li6: "Knowledge about straightner",
            li7: "Knowledge about hairsprays",
        },
        {
            id: 3,
            title: "Hairstyle",
            li1: "Mousse knowledge",
            li2: "Hair extension settings",
            li3: "Pulling technique",
            li4: "Voluminous hair using stuffing",
            li5: "Types of curls",
            li6: "Back combing techniques",
            li7: "Hair sectioning & Parting",
        },
        {
            id: 3,
            title: "Hairstyle",
            li1: "Messy bun",
            li2: "Messy braids",
            li3: "Bridal hairstyles",
            li4: "Reception hair - do",
            li5: "Fixing tikka",
            li6: "Different types of front variations",
        },
        {
            id: 3,
            title: "Saree",
            li1: "Saree drapping",
            li2: "Ironing",
            li3: "Box folding",
            li4: "10 different styles of draping",
        },
    ]

    const [filterType, setFilterType] = useState<string>('1');
    const handleFilterClick = (type: string) => {
        setFilterType(type);
    };
    return (
        <div className="bg-[url('/assets/images/experience.jpg')] bg-no-repeat w-full bg-cover bg-center bg-fixed ">
            <div className='flex justify-center items-center py-5'>
                <h1 className='md:text-3xl text-2xl font-semibold md:p-5 p-3 text-primary-500 w-fit'>
                    <span className='text-black '>Courses</span> We Offer
                    <div className='py-2'>
                        <hr className='border border-primary-400 ' />
                    </div>
                </h1>
            </div>
            <div className='pt-10'>
                <div className='px-5 flex flex-wrap gap-5 justify-center'>
                    <button className={`${filterType === '1' ? 'bg-primary-300 px-9 py-1 font-bold rounded-full border-2 border-primary-400' : 'coursebtn'}`} onClick={() => handleFilterClick('1')}> <span>Basic Beautician Course</span> </button>
                    <button className={`${filterType === '2' ? 'bg-primary-300 px-9 py-1 font-bold rounded-full border-2 border-primary-400' : 'coursebtn'}`} onClick={() => handleFilterClick('2')}> <span>Advance Beautician Course</span> </button>
                    <button className={`${filterType === '3' ? 'bg-primary-300 px-9 py-1 font-bold rounded-full border-2 border-primary-400' : 'coursebtn'}`} onClick={() => handleFilterClick('3')}> <span>Advance Make-up &amp; hairStyle Course</span> </button>
                </div>

                <CourseFilter data={data} filterById={filterType} />
            </div>
        </div>
    )
}

export default CourseHead